### ISSUE TITLE
Images :)

### ISSUE THREAD

**Issue by maurizzzio** [maurizzzio/simple-function-plot#1]

**Comment by maurizzzio** [comment]
![screen shot 2015-03-31 at 3 04 07 am](https://cloud.githubusercontent.com/assets/1616682/6913872/309d9b44-d753-11e4-8dfc-912ece8b120c.png)

**Comment by maurizzzio** [comment]
![simple-function-plot](https://cloud.githubusercontent.com/assets/1616682/6913963/11013696-d754-11e4-8bf1-8008f36cd670.gif)

**Comment by mauriciopoppe** [comment]
![image](https://user-images.githubusercontent.com/1616682/93041565-a9a84980-f601-11ea-900e-4e6809b5fa96.png)

**Comment by mauriciopoppe** [comment]
![image](https://user-images.githubusercontent.com/1616682/93912098-23060300-fcb8-11ea-823f-be8dfe9c24b9.png)

**Comment by mauriciopoppe** [comment]
![image](https://user-images.githubusercontent.com/1616682/93946415-0edcf880-fcee-11ea-9002-13ef44ae4f5f.png)

**Comment by mauriciopoppe** [comment]
![Image](https://github.com/user-attachments/assets/14de26ec-619b-4c52-b572-6c8efde28151)

**Comment by mauriciopoppe** [comment]
![Image](https://github.com/user-attachments/assets/aa26a57e-b556-482c-8cce-13b22b2e412d)

**Comment by mauriciopoppe** [comment]
![Image](https://github.com/user-attachments/assets/d252cf9d-e9b0-4bce-9791-c07f820b38c9)

**Comment by mauriciopoppe** [comment]
![Image](https://github.com/user-attachments/assets/c251efdd-66de-4bab-bbbb-ffc0e77eae3d)
